sed $1  -i -e 's/fprint/sscan/g'
sed $1  -i -e 's/fp/argv\[argcount+1\]/g'
sed $1  -i -e 's/%g/%lf/g'
sed $1  -i -e 's/  "/"/g'
sed $1  -i -e 's/10  %/%/g'
sed $1  -i -e 's/11  %/%/g'
sed $1  -i -e 's/12  %/%/g'
sed $1  -i -e 's/13  %/%/g'
sed $1  -i -e 's/14  %/%/g'
sed $1  -i -e 's/15  %/%/g'
sed $1  -i -e 's/16  %/%/g'
sed $1  -i -e 's/17  %/%/g'
sed $1  -i -e 's/18  %/%/g'
sed $1  -i -e 's/19  %/%/g'
sed $1  -i -e 's/20  %/%/g'
sed $1  -i -e 's/21  %/%/g'
sed $1  -i -e 's/22  %/%/g'
sed $1  -i -e 's/23  %/%/g'
sed $1  -i -e 's/24  %/%/g'
sed $1  -i -e 's/25  %/%/g'
sed $1  -i -e 's/26  %/%/g'
sed $1  -i -e 's/27  %/%/g'
sed $1  -i -e 's/28  %/%/g'
sed $1  -i -e 's/29  %/%/g'
sed $1  -i -e 's/30  %/%/g'
sed $1  -i -e 's/31  %/%/g'
sed $1  -i -e 's/32  %/%/g'
sed $1  -i -e 's/33  %/%/g'
sed $1  -i -e 's/34  %/%/g'
sed $1  -i -e 's/0  %/%/g'
sed $1  -i -e 's/1  %/%/g'
sed $1  -i -e 's/2  %/%/g'
sed $1  -i -e 's/3  %/%/g'
sed $1  -i -e 's/4  %/%/g'
sed $1  -i -e 's/5  %/%/g'
sed $1  -i -e 's/6  %/%/g'
sed $1  -i -e 's/7  %/%/g'
sed $1  -i -e 's/8  %/%/g'
sed $1  -i -e 's/9  %/%/g'
sed $1  -i -e 's/"-$2%/"%/g'

